plugins {
    id 'java'
}

repositories {
    mavenCentral()
    maven { url "https://www.jitpack.io" }
}

dependencies {
    compileOnly "com.github.Anuken:Arc:1.139.1"
    compileOnly "com.github.Anuken:Mindustry:v146"
}

jar {
    archiveName = "RedTeamAI.jar"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
